name: build

on:
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main ]
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: install tools
      run: |
        sudo apt install tmux
        go install github.com/golang/mock/mockgen@latest

    - name: Vet
      run: make vet

    - name: Testing
      run: make test

    - name: Build
      run: make build

    - uses: actions/upload-artifact@master
      with:
        name: release-artifact
        path: dist
