---
name: "tagged-release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    uses: dustinliu/nvclient/.github/workflows/build.yml@main

  tagged-release:
    name: "Tagged Release"
    runs-on: "ubuntu-latest"
    needs: build

    steps:
    - uses: actions/download-artifact@master
      with:
        name: release-artifact

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
        files: |
          dist/*
